# Generated by Django 5.1.4 on 2026-02-19 07:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeEvaluation',
            fields=[
                ('scheme_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=500)),
                ('scheme_type', models.CharField(blank=True, default='', max_length=200)),
                ('ministry', models.CharField(blank=True, default='', max_length=300)),
                ('benefit_summary', models.TextField(blank=True, default='')),
                ('max_benefit', models.CharField(blank=True, default='', max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('extracted_rules', models.JSONField(blank=True, default=list)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('application_steps', models.JSONField(blank=True, default=list)),
                ('deadline', models.CharField(blank=True, default='', max_length=200)),
                ('official_portal', models.CharField(blank=True, default='', max_length=500)),
                ('evaluation_result', models.JSONField(blank=True, default=dict)),
                ('match_percentage', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Eligible', 'Eligible'), ('Partial', 'Partial'), ('Not Eligible', 'Not Eligible')], default='Not Eligible', max_length=20)),
                ('language_preference', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Marathi', 'Marathi')], default='English', max_length=20)),
                ('chat_history', models.JSONField(blank=True, default=list)),
                ('source_pdf', models.FileField(blank=True, null=True, upload_to='scheme_pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
